### ISSUE TITLE
Add new magisk module for other features

### ISSUE THREAD

**Issue by elswerky** [Fede2782/oneCompleter-Legacy#44]
Hello 
I have issues with oneui 5.1.1 where xposed module named xposed edge doesn't work 

So I revert back to s6 lite oneui 5.1 
But am missing new features in oneui 5.1.1 like text extractor 

So please can you make module with most important features like 
Text extractor 
Gallery full editor with eraser and others
Gallery object capture feature 

Plz if possible 

I just don't want other features like bootNimation change and ar drawer and others 

Just 3 features I mentioned if possible 

Thank you 

Aldo if possible if you telegram id

**Comment by Fede2782** [comment]
Download custom build here [https://quickshare.samsungcloud.com/bXM9roIUdfqQ](url)
It has these three features for One UI 5.1. Tell me if Photo Editor works because the 5.1.1 version is included, it should work but tell me if it does so.

**Comment by elswerky** [comment]
Bro
This link you provided doesn't open anything 
Can you please give mule your telegram ID for easy access

Or can you send me any message on telegram  @elswerky
