### ISSUE TITLE
Bro closed thread of mine befire

### ISSUE THREAD

**Issue by elswerky** [Fede2782/oneCompleter-Legacy#45]
Bro.
You closed thread I was asking fir custom zip
And provided a link from quick share which doesn't open with me 
Plz if you can send me any message on telegram @elswerky 
Or send me your telegram ID 

The link you provided not opening for me , may be it had a timer

**Comment by Fede2782** [comment]
I closed the topic because it is not linked to oneCompleter but i'll be glad to send you a custom file. There was an error in the link generated. My telegram is @Fede2782

**Comment by Fede2782** [comment]
https://quickshare.samsungcloud.com/58NdwkXmrwp1
